# Generated by Django 5.2 on 2025-04-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=20)),
                ('entity', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('changes', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('log_level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'action'], name='logger_audi_user_id_f41f7e_idx'), models.Index(fields=['entity', 'entity_id'], name='logger_audi_entity_8bf87a_idx'), models.Index(fields=['timestamp'], name='logger_audi_timesta_23d86d_idx')],
            },
        ),
    ]
